---
- name: Install bind packages
  apt:
    name: "{{ bind_apt_packages }}"
    state: present
    update_cache: yes

- name: Ensure {{ bind_service_name }} service started and start up at boot
  systemd:
    name: "{{ bind_service_name }}"
    state: started
    enabled: yes
