---
- name: Add custom lines in bind9 local configuration file
  lineinfile:
    path: "{{ bind_config_local_file_path }}"
    line: "{{ item }}"
    state: present
  with_items: "{{ bind_config_local_custom }}"
  notify: Restart Bind

- name: Add custom content in bind9 options configuration file
  blockinfile:
    path: "{{ bind_config_options_file_path }}"
    insertafter: "^options {"
    block: "{{ bind_config_options_custom }}"
    state: present
  when: bind_config_options_custom is defined
  notify: Restart Bind
