---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  
- include_tasks: bind_pre.yml
- include_tasks: bind_install.yml

- block: # Config Bind
  - include_tasks: bind_search_config.yml
  - include_tasks: bind_post.yml
  tags:
    - bind-config
